# Template: permite que a API impersone o usuário USER_NAME.
# Substitua USER_NAME. Para N usuários, adicione mais itens em resourceNames.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: impersonate-USER_NAME
rules:
  - apiGroups: [""]
    resources: ["users"]
    resourceNames: ["USER_NAME"]
    verbs: ["impersonate"]
  - apiGroups: [""]
    resources: ["groups"]
    verbs: ["impersonate"]
